version: "3.8"

services:
  db:
    image: postgres:15
    container_name: shopapi-postgres
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    ports:
      - "5432:5432"
    volumes:
      - shopdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  shopdata: